parameters:
#    lilaconcepts_bestpractice.example.class: LilaConcepts\LilaConceptsBestPracticeBundle\Example

services:
#    lilaconcepts_bestpractice.example:
#        class: %lilaconcepts_bestpractice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
